services:
  mysql:
    restart: always
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    image: mysql:9
    container_name: my-test-project-mysql-container
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'UTC'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  mysql_test:
    restart: always
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    image: mysql:9
    container_name: my-test-project-mysql-test-container
    ports:
      - "${TEST_DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${TEST_DB_NAME}
      MYSQL_USER: ${TEST_DB_USER}
      MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
      TZ: 'UTC'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/mysql_test/data:/var/lib/mysql
      - ./.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
