version: '3'

services:
  db:
    restart: always
    image: mysql:9
    container_name: my-test-project-container
    ports:
      - "15351:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yuckyjuice
      MYSQL_DATABASE: mytestprojectmysql01
      MYSQL_USER: localuser
      MYSQL_PASSWORD: yuckyjuice
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/sql:/docker-entrypoint-initdb.d
