// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package infra

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, name string) (int64, error)
	DeleteUser(ctx context.Context, id int64) error
	GetUser(ctx context.Context, id int64) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
}

var _ Querier = (*Queries)(nil)
