apiVersion: v1
kind: Service
metadata:
  name: my-test-app-service
  labels:
    app: my-test-app
spec:
  type: LoadBalancer
  selector:
    app: my-test-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
