name: "[dev] CI"

permissions:
  contents: read       # checkout や vars.GCP_* の読み取り用
  id-token: write      # OIDC トークン発行のために必須

on:
  workflow_dispatch:

jobs:
  dev-deploy:
    uses: ./.github/workflows/ci-shared.yml
    with:
      env: dev
