name: "Test"

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: "checkout"
        name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          persist-credentials: false
      - id: "setup-go"
        name: "Go setup"
        uses: "./.github/actions/go-setup"
      - id: "start-mysql"
        name: "Start MySQL"
        shell: bash
        run: |
          make run-local-mysql-test
      - id: "migrate-db"
        name: "Migrate DB"
        shell: bash
        run: |
          make test-migrate-up
      - id: "run-tests"
        name: "Run tests"
        shell: bash
        run: |
          make test
